[package]
name = "contain-rs-nginx"
version = "0.1.0"
edition = "2021"

[dependencies]
contain-rs-core = { path = "../../contain-rs-core" }
contain-rs-macro = { path = "../../contain-rs-macro" }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
