[package]
name = "contain-rs-nginx"
version = "0.2.1"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
contain-rs = { path = "../../contain-rs", features = ["macros"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
