[workspace]

members = [
    "contain-rs",
    "contain-rs-core",
    "contain-rs-macro",
    "contain-rs-parser",
    "images/contain-rs-postgres",
    "images/contain-rs-nginx",
    "images/contain-rs-surrealdb",
]
