[package]
name = "contain-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
log = "0.4"
regex = "1.5"

[dev-dependencies]
pretty_env_logger = "0.4.0"