[package]
name = "contain-rs-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
contain-rs-core = { path = "../contain-rs-core" }
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true, features = ["span-locations"] }
regex = { workspace = true }
