[package]
name = "contain-rs-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contain-rs = { path = "../contain-rs" }
syn = { version = "1.0", features = ["full" ,"extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
