[package]
name = "contain-rs-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
contain-rs-core = { path = "../contain-rs-core" }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
