name: Create Git Tag
description: Create a git release tag and push it

inputs:
  crate-path:
    description: path of the crate to create the tag for
    required: true

runs:
  using: composite
  steps:
    - run: |
        cd ${{ inputs.crate-path }}
        export VERSION=$(cargo get version)
        git tag -a ${{ inputs.crate-path }}-${VERSION} -m "Release ${{ inputs.crate-path }} ${VERSION}"
        git push origin ${{ inputs.crate-path }}-${VERSION}
      shell: bash
