name: Publish Crate
description: Publishes a crate to crates.io

inputs:
  crate:
    description: The name of the crate
    required: true

runs:
  using: composite
  steps:
    - run: |
        cargo publish -p ${{ inputs.crate }}
      shell: bash
