[package]
name = "contain-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "contain-rs image macro"
repository = "https://github.com/reenigneEsrever92/contain-rs"
documentation = "https://docs.rs/contain-rs"
readme = "README.md"
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contain-rs-rt = { path = "../contain-rs-rt" }
