[package]
name = "contain-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "contain-rs image macro"
repository = "https://github.com/reenigneEsrever92/contain-rs"
documentation = "https://docs.rs/contain-rs"
readme = "README.md"
categories = ["development-tools::testing"]

[features]
macros = []

[dependencies]
contain-rs-core = { path = "../contain-rs-core" }
contain-rs-macro = { path = "../contain-rs-macro" }
