[package]
name = "contain-rs-surrealdb"
version = "0.1.0"
edition = "2021"

[dependencies]
contain-rs = { path = "../../contain-rs", features = ["macros"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
log = { workspace = true }
