[package]
name = "contain-rs-surrealdb"
version = "0.1.0"
edition = "2021"

[dependencies]
contain-rs = { path = "../../contain-rs", features = ["macros"] }

[dev-dependencies]
reqwest = { version = "0.11" }
log = "0.4"
pretty_env_logger = "0.4"
