[package]
name = "contain-rs-surrealdb"
version = "0.2.0"
edition = "2021"

[dependencies]
contain-rs = { path = "../../contain-rs", features = ["macros"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["blocking"] }
tracing-subscriber = { workspace = true }
