[package]
name = "contain-rs-macro"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
contain-rs-parser = { path = "../contain-rs-parser" }
contain-rs-core = { path = "../contain-rs-core" }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "1.0"
