name: Increment Version
description: Increment the version of the crate at the specified path

inputs:
  level:
    description: Version level to increment (major, minor, patch)
    required: true

runs:
  using: composite
  steps:
    - run: |
        cargo workspaces bump ${{ inputs.level }}
      shell: bash
