name: Release Minor

on:
  workflow_dispatch:
    secrets:
      CRATES_IO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Prepare
        run: |
          cargo install cargo-bump
          cargo install cargo-get
      - name: Crates.io Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        crate:
          [
            "contain-rs-core",
            "contain-rs-parser",
            "contain-rs-macro",
            "contain-rs-nginx",
            "contain-rs-postgres",
            "contain-rs-surrealdb",
            "contain-rs",
          ]

    steps:
      - uses: ./.github/workflows/publish-crate.yml
        with:
          crate: ${{ matrix.crate }}

  git-house-keeping:
    runs-on: ubuntu-latest
    needs: publish
    strategy:
      matrix:
        crate-path:
          [
            "contain-rs-core",
            "contain-rs-parser",
            "contain-rs-macro",
            "images/contain-rs-nginx",
            "images/contain-rs-postgres",
            "images/contain-rs-surrealdb",
            "contain-rs",
          ]
        level: ["minor"]
    steps:
      - uses: ./.github/workflows/create-git-tag.yml
        with:
          crate-path: ${{ matrix.crate-path }}
      - uses: ./.github/workflows/increment-version.yml
        with:
          crate-path: ${{ matrix.crate-path }}
          level: ${{ matrix.level }}
