name: Release Patch

on:
  workflow_dispatch:
    secrets:
      CRATES_IO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Prepare
        run: |
          cargo install cargo-workspaces
          cargo install cargo-get
      - name: Crates.io Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish All
        run: |
          cargo workspaces publish -y
      # - name: Create Tag
      #   run: |
      #     export VERSION=$(cargo get version)
      #     git tag -a ${VERSION} -m "Release ${VERSION}"
      #     git push origin ${VERSION}
      - name: Increment Version
        run: |
          cargo workspaces version -y patch
