name: Release Pre Patch

on:
  workflow_dispatch:
    secrets:
      CRATES_IO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{secrets.CRATES_IO_TOKEN}}
      - uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: publish --no-git-tag -y prerelease
