name: Release Minor

on:
  workflow_dispatch:
    secrets:
      CRATES_IO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - crate: "contain-rs-core"
            path: "contain-rs-core"
          - crate: "contain-rs-parser"
            path: "contain-rs-parser"
          - crate: "contain-rs-macro"
            path: "contain-rs-macro"
          - crate: "contain-rs-nginx"
            path: "images/contain-rs-nginx"
          - crate: "contain-rs-postgres"
            path: "images/contain-rs-postgres"
          - crate: "contain-rs-surrealdb"
            path: "images/contain-rs-surrealdb"

    steps:
      - uses: actions/checkout@v1
      - uses: fregante/setup-git-user@v1
      - name: Prepare
        run: |
          cargo install cargo-bump
          cargo install cargo-get
          pwd
          ls -la .
          ls -la ./.github
          ls -la ./.github/actions
      - name: Crates.io Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - uses: ./.github/actions/publish-crate.yml
        with:
          crate: ${{ matrix.crate }}
      - uses: ./.github/actions/create-git-tag.yml
        with:
          crate-path: ${{ matrix.path }}
      - uses: ./.github/actions/increment-version.yml
        with:
          crate-path: ${{ matrix.path }}
          level: ${{ matrix.level }}
