name: Release Pre Patch

on:
  workflow_dispatch:
    secrets:
      CRATES_IO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces
      - uses: actions-rs/cargo@v1
        with:
          command: login ${{secrets.CRATES_IO_TOKEN}}
      - uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: publish -y prepatch
