name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: podman "run" "-d" "--name" "contain-rs-KIWi8MEQ" "--health-cmd" "curl http://localhost || exit 1" "docker.io/library/nginx:latest" 
